### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by StoveJunJun** [dualplus/LTNet#2]
C:\Software\Anaconda3\envs\Caffe\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "eval_cifar10.py", line 93, in <module>
    display_validation_test_result(model_weight, device_no = device_no)
  File "eval_cifar10.py", line 87, in display_validation_test_result
    device_no = device_no)
  File "eval_cifar10.py", line 47, in eval_validation
    for line in freader:
ValueError: I/O operation on closed file.

**Comment by StoveJunJun** [comment]
> C:\Software\Anaconda3\envs\Caffe\lib\site-packages\skimage\transform_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
> warn("The default mode, 'constant', will be changed to 'reflect' in "
> Traceback (most recent call last):
> File "eval_cifar10.py", line 93, in 
> display_validation_test_result(model_weight, device_no = device_no)
> File "eval_cifar10.py", line 87, in display_validation_test_result
> device_no = device_no)
> File "eval_cifar10.py", line 47, in eval_validation
> for line in freader:
> ValueError: I/O operation on closed file.

46行改成
with open(validation_img_list, 'r') as freader:
完美解决
